language: python

python:
  - "3.6"

install:
  - pip install Cython
  - pip install twine
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - python -m unittest discover tests
  - python setup.py bdist_wheel sdist

branches:
  only:
  - master

deploy:
- provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: "dist/*.{whl,tar.gz}"
  skip_cleanup: true
  draft: true
  tags: false
- provider: pypi
  user: "__token__"
  password: "$PYPI_TOKEN"