language: python

python:
  - "3.6"

install:
  - pip install Cython
  - pip install -r recoengi/requirements.txt
  - pip install .
# command to run tests
script:
  - python -m unittest discover tests

branches:
  only:
  - master

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - dist/*.whl
    - dist/*.tar.gz
  skip_cleanup: true
  draft: true
  tags: false