language: python

python:
  - "3.6"

install:
  - pip install Cython
  - pip install -r recoengi/requirements.txt
  - pip install .
# command to run tests
script:
  - python -m unittest discover tests
  - python setup.py bdist_wheel

branches:
  only:
  - master

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  package_glob: 
    - "dist/*.whl"
    - "dist/*.tar.gz"
  skip_cleanup: true
  draft: true
  tags: false